### ISSUE TITLE
sharedEdge forever loop

### ISSUE THREAD

**Issue by MartensCedric** [nzfeng/SWN#2]
Opening this issue to document the issue [here](https://github.com/nzfeng/SWN/blob/cb308ee8d01a46cecf6d3ee1f1b9d51cdc53962b/src/utils.cpp#L435)

>             const SurfacePoint& pt1 = curveNodes[seg[0]];
>             const SurfacePoint& pt2 = curveNodes[seg[1]];
> 
>             // For some reason, very occasionally this code fails. I checked that pt2 is indeed among the adjacent
>             // vertices of pt1; the == operator among vertices just doesn't work sometimes, I guess.
>             Edge e = sharedEdge(pt1, pt2);

I'm not sure the issue I am experiencing is the same as what the comment references. 

I can reproduce my issue with these two files: 
[ico.zip](https://github.com/nzfeng/SWN/files/12525472/ico.zip)

Running `./main --headless --V ico.obj --c=ico_with_curve.obj --output="out.txt"`

I might be misunderstanding on how to actually input curves properly, but using my input.

This results in a while loop in `sharedEdge`, I highly suspect this is due to the garbage index in pt1/pt2 which happens to be the same 
![image](https://github.com/nzfeng/SWN/assets/18620025/f88b751b-afcb-48a4-8e6c-7e5edc65c2e3)

I will investigate this later but I need to eat and go to class

update 1: it's because in the examples, the curve file's `v`s are integers while I have three floats as coordinates.

**Comment by WinterAlexander** [comment]
Having the same issue

**Comment by nzfeng** [comment]
Ah, I think this arises from the README perhaps being written not so clearly (in the section "Curve input").

If you have specified the curve **via OBJ line elements**, you can simply execute the program with one argument: the OBJ file. For example, I'm able to run your example without issue by calling
```
bin/main ico_with_curve.obj
```
(Here I've solved for the winding number on an intrinsic mesh just for fun.)
![image](https://github.com/nzfeng/SWN/assets/27327961/6c43fe8c-f65b-4030-830d-542427ea3efe)

The second "input" argument for the curve file is only necessary if you've specified your curve **via barycentric points** on the mesh, which includes vertices specified by index. The example data included as part of the repo contain examples of both types of curve input.

The reason I decided to separate curve input this way is because the OBJ file format also has `v` and `e` elements, which overlap with how I would think are the most intuitive way to specify barycentric points. If this continues to be a point of confusion, I can change the barycentric point specification, for example by using an additional `b` char and using a different char besides `l` to indicate segments between barycentric points.

**Comment by MartensCedric** [comment]
Thanks @nzfeng!
